import type { Metadata } from "next";
import Providers from "@/app/Components/Provider";

export const metadata: Metadata = {
  title: "Video Auth Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
